-- Comercial Vanderley: atualizacao de precos a partir das fotos de etiquetas de 09/10/2026.
-- Idempotente: cria apenas produtos ausentes (por slug) e atualiza o preco mais recente da loja.
-- Fora desta carga: etiquetas com nome/tamanho ilegivel ou ambiguo.

insert into public.products (name, brand, category, size, unit, slug)
select v.name, v.brand, v.category, v.size, v.unit, v.slug
from (values
  ('Biscoito Doce Mabel Chocolate', 'Mabel', 'biscoitos', '300g', 'un', 'biscoito-doce-mabel-chocolate'),
  ('Biscoito Maisena Mabel', 'Mabel', 'biscoitos', '300g', 'un', 'biscoito-maisena-mabel'),
  ('Biscoito Maizena Tradicional Vitarella', 'Vitarella', 'biscoitos', '350g', 'un', 'biscoito-maizena-tradicional-vitarella'),
  ('Biscoito Doce Belma Coco Zero Lactose', 'Belma', 'biscoitos', '300g', 'un', 'biscoito-doce-belma-coco-zero-lactose'),
  ('Biscoito Doce Belma Leite Zero Lactose', 'Belma', 'biscoitos', '300g', 'un', 'biscoito-doce-belma-leite-zero-lactose'),
  ('Biscoito Doce Belma Maizena Zero Lactose', 'Belma', 'biscoitos', '300g', 'un', 'biscoito-doce-belma-maizena-zero-lactose'),
  ('Água Mineral Cristal 5L', 'Cristal', 'bebidas', '5L', 'un', 'agua-mineral-cristal-5l'),
  ('Arroz Phd Polido 1kg', 'PHD', 'mercearia', '1kg', 'un', 'arroz-phd-polido-1kg'),
  ('Biscoito Doce Laminado Vivale Leite 300g', 'Vivale', 'biscoitos', '300g', 'un', 'biscoito-doce-laminado-vivale-leite-300g'),
  ('Kit Pantene Shampoo 350ml + Condicionador 175ml Liso Extremo', 'Pantene', 'cabelo', 'kit', 'un', 'kit-pantene-shampoo-350ml-condicionador-175ml-liso-extremo'),
  ('Bebida Láctea Morango Bob Esponja 200ml', 'Bob Esponja', 'laticinios', '200ml', 'un', 'bebida-lactea-morango-bob-esponja-200ml'),
  ('Macarrão Instantâneo Sandella Galinha 85g', 'Sandella', 'mercearia', '85g', 'un', 'macarrao-instantaneo-sandella-galinha-85g'),
  ('Sabonete Albany Leite de Coco 85g', 'Albany', 'higiene', '85g', 'un', 'sabonete-albany-leite-de-coco-85g'),
  ('Creme Dental Colgate Tripla Ação 120g', 'Colgate', 'bucal', '120g', 'un', 'creme-dental-colgate-tripla-acao-120g'),
  ('Biscoito Wafer Minueto Brigadeiro 73g', 'Minueto', 'biscoitos', '73g', 'un', 'biscoito-wafer-minueto-brigadeiro-73g'),
  ('Creme Dental Colgate Tripla Ação 180g', 'Colgate', 'bucal', '180g', 'un', 'creme-dental-colgate-tripla-acao-180g'),
  ('Pão de Queijo Pão e Arte Tradicional 1kg', null, 'congelados', '1kg', 'un', 'pao-de-queijo-pao-e-arte-tradicional-1kg'),
  ('Pão de Queijo Norte Minas 1kg', null, 'congelados', '1kg', 'un', 'pao-de-queijo-norte-minas-1kg'),
  ('Biscoito Wafer Minueto Pe de Moleque 73g', 'Minueto', 'biscoitos', '73g', 'un', 'biscoito-wafer-minueto-pe-de-moleque-73g'),
  ('Sabonete Albany Perfumes da Natureza Frutas Vermelhas 85g', 'Albany', 'higiene', '85g', 'un', 'sabonete-albany-perfumes-da-natureza-frutas-vermelhas-85g'),
  ('Sabão em Pó Omo Lavagem Perfeita 1,4kg', 'Omo', 'limpeza', '1.4kg', 'un', 'sabao-em-po-omo-lavagem-perfeita-1-4kg'),
  ('Batata McCain Corte Fino 7mm 2,25kg', 'McCain', 'mercearia', '2.25kg', 'un', 'batata-mccain-corte-fino-7mm-2-25kg'),
  ('Limpador Perfumado Casa Flor 500ml', 'Casa Flor', 'limpeza', '500ml', 'un', 'limpador-perfumado-casa-flor-500ml'),
  ('Detergente Zupp Açaí 500ml', 'Zupp', 'limpeza', '500ml', 'un', 'detergente-zupp-acai-500ml'),
  ('Detergente Zupp Ultra 500ml', 'Zupp', 'limpeza', '500ml', 'un', 'detergente-zupp-ultra-500ml'),
  ('Detergente Zupp Clear 500ml', 'Zupp', 'limpeza', '500ml', 'un', 'detergente-zupp-clear-500ml'),
  ('Sabão Barra Brisa Glicerinado Neutro 800g', 'Brisa', 'limpeza', '800g', 'un', 'sabao-barra-brisa-glicerinado-neutro-800g'),
  ('Amaciante Brisa Carinho 2L', 'Brisa', 'limpeza', '2L', 'un', 'amaciante-brisa-carinho-2l'),
  ('Multi-inseticida Pro Inset Ação Total 350ml', 'Pro Inset', 'limpeza', '350ml', 'un', 'multi-inseticida-pro-inset-acao-total-350ml'),
  ('Multi-inseticida Pro Inset Eucalipto 350ml', 'Pro Inset', 'limpeza', '350ml', 'un', 'multi-inseticida-pro-inset-eucalipto-350ml'),
  ('Multi-inseticida Pro Inset Mata Baratas e Formigas 350ml', 'Pro Inset', 'limpeza', '350ml', 'un', 'multi-inseticida-pro-inset-mata-baratas-e-formigas-350ml'),
  ('Amaciante Minuano Brisa Macia 2L', 'Minuano', 'limpeza', '2L', 'un', 'amaciante-minuano-brisa-macia-2l'),
  ('Amaciante Minuano Noite de Lua 2L', 'Minuano', 'limpeza', '2L', 'un', 'amaciante-minuano-noite-de-lua-2l'),
  ('Pão de Queijo Pão e Arte Tradicional 400g', null, 'congelados', '400g', 'un', 'pao-de-queijo-pao-e-arte-tradicional-400g'),
  ('Pão de Queijo Coquetel Norte Minas 400g', null, 'congelados', '400g', 'un', 'pao-de-queijo-coquetel-norte-minas-400g'),
  ('Sabão Barra Brisa Lavanda e Coco Lilas 800g', 'Brisa', 'limpeza', '800g', 'un', 'sabao-barra-brisa-lavanda-e-coco-lilas-800g'),
  ('Sabão Barra Brisa Glicerinado Limão 800g', 'Brisa', 'limpeza', '800g', 'un', 'sabao-barra-brisa-glicerinado-limao-800g'),
  ('Desinfetante Ypê Bak Floral 500ml', 'Ypê', 'limpeza', '500ml', 'un', 'desinfetante-ype-bak-floral-500ml'),
  ('Limpador Perfumado Veja Lavanda 500ml', 'Veja', 'limpeza', '500ml', 'un', 'limpador-perfumado-veja-lavanda-500ml'),
  ('Vanish Oxi Action Pink Sachê sem Cloro 120g', 'Vanish', 'limpeza', '120g', 'un', 'vanish-oxi-action-pink-sache-sem-cloro-120g'),
  ('Vanish Pó sem Cloro White 120g', 'Vanish', 'limpeza', '120g', 'un', 'vanish-po-sem-cloro-white-120g'),
  ('Tira Manchas Vanish Oxi Action 400g', 'Vanish', 'limpeza', '400g', 'un', 'tira-manchas-vanish-oxi-action-400g'),
  ('Sabão Líquido Mon Bijou Neutro 300ml', 'Mon Bijou', 'limpeza', '300ml', 'un', 'sabao-liquido-mon-bijou-neutro-300ml'),
  ('Lava Roupas Líquido Omo Ação Total 750ml', 'Omo', 'limpeza', '750ml', 'un', 'lava-roupas-liquido-omo-acao-total-750ml'),
  ('Batata Palito Farm Frites Potato 2,5kg', 'Farm Frites', 'congelados', '2.5kg', 'un', 'batata-palito-farm-frites-potato-2-5kg'),
  ('Cerveja Corona Extra 6 Garrafas 330ml', 'Corona', 'bebidas', '6x330ml', 'un', 'cerveja-corona-extra-6-garrafas-330ml'),
  ('Creme Dental Colgate Carvão Natural Extracts 70g', 'Colgate', 'bucal', '70g', 'un', 'creme-dental-colgate-carvao-natural-extracts-70g'),
  ('Sabão em Pó Brisa Floral Bicarbonato 400g', 'Brisa', 'limpeza', '400g', 'un', 'sabao-em-po-brisa-floral-bicarbonato-400g'),
  ('Sabão em Pó Brisa Lavanda e Coco 400g', 'Brisa', 'limpeza', '400g', 'un', 'sabao-em-po-brisa-lavanda-e-coco-400g'),
  ('Lava Roupas em Pó Zupp 800g', 'Zupp', 'limpeza', '800g', 'un', 'lava-roupas-em-po-zupp-800g'),
  ('Sabão em Pó Brisa Lavanda e Coco 800g', 'Brisa', 'limpeza', '800g', 'un', 'sabao-em-po-brisa-lavanda-e-coco-800g'),
  ('Detergente Ypê Clear Care 500ml', 'Ypê', 'limpeza', '500ml', 'un', 'detergente-ype-clear-care-500ml'),
  ('Desodorante Nivea Original Protect 150ml', 'Nivea', 'higiene', '150ml', 'un', 'desodorante-nivea-original-protect-150ml'),
  ('Desodorante Francis Aerossol Azul Men Active Sport 150ml', 'Francis', 'higiene', '150ml', 'un', 'desodorante-francis-aerossol-azul-men-active-sport-150ml'),
  ('Desodorante Aero Francis Men Ultra Fresh', 'Francis', 'higiene', '150ml', 'un', 'desodorante-aero-francis-men-ultra-fresh'),
  ('Desodorante Above Peaceful Farhion 150ml', 'Above', 'higiene', '150ml', 'un', 'desodorante-above-peaceful-farhion-150ml'),
  ('Presunto Cozido (preço por kg)', null, 'acougue', 'kg', 'kg', 'presunto-cozido-preco-por-kg'),
  ('Cerveja Amstel Lata 269ml (cx 12)', 'Amstel', 'bebidas', '12x269ml', 'un', 'cerveja-amstel-lata-269ml-cx-12'),
  ('Creme Dental Sorriso Kolynos 90g', 'Sorriso', 'bucal', '90g', 'un', 'creme-dental-sorriso-kolynos-90g'),
  ('Detergente Zupp Limão 500ml', 'Zupp', 'limpeza', '500ml', 'un', 'detergente-zupp-limao-500ml'),
  ('Caixa Cerveja Skol Pilsen 15x269ml', 'Skol', 'bebidas', '15x269ml', 'un', 'caixa-cerveja-skol-pilsen-15x269ml'),
  ('Batata Palito Star Frites 2kg', 'Star Frites', 'congelados', '2kg', 'un', 'batata-palito-star-frites-2kg'),
  ('Desodorante Aero Above Sport 150ml', 'Above', 'higiene', '150ml', 'un', 'desodorante-aero-above-sport-150ml'),
  ('Desodorante Above Women Lady 150ml', 'Above', 'higiene', '150ml', 'un', 'desodorante-above-women-lady-150ml'),
  ('Biscoito Marilan Pit Stop Original 137g', 'Marilan', 'biscoitos', '137g', 'un', 'biscoito-marilan-pit-stop-original-137g'),
  ('Biscoito Rosquinha Tradicional Marilan Sabor Coco 500g', 'Marilan', 'biscoitos', '500g', 'un', 'biscoito-rosquinha-tradicional-marilan-sabor-coco-500g'),
  ('Caixa Cerveja Antarctica Pilsen 15x269ml', 'Antarctica', 'bebidas', '15x269ml', 'un', 'caixa-cerveja-antarctica-pilsen-15x269ml'),
  ('Leite de Coco Qualicoco VD 500ml', 'Qualicoco', 'laticinios', '500ml', 'un', 'leite-de-coco-qualicoco-vd-500ml'),
  ('Leite de Coco Qualicoco VD 200ml', 'Qualicoco', 'laticinios', '200ml', 'un', 'leite-de-coco-qualicoco-vd-200ml'),
  ('Leite de Coco Copra VD 200ml', 'Copra', 'laticinios', '200ml', 'un', 'leite-de-coco-copra-vd-200ml'),
  ('Caixa Cerveja Brahma Chopp 15x269ml', 'Brahma', 'bebidas', '15x269ml', 'un', 'caixa-cerveja-brahma-chopp-15x269ml')
) as v(name, brand, category, size, unit, slug)
where not exists (select 1 from public.products p where p.slug = v.slug);

with desired(slug, value) as (
  values
    ('flocao-de-milho-sinha-400g', 3.00::numeric),
    ('achocolatado-nescau-nestle-350g', 9.99),
    ('biscoito-miragina-agua-e-sal-330g', 5.00),
    ('lava-roupas-em-po-tixan-ype-maciez-800g', 13.99),
    ('arroz-kumbuca-branco-tipo-1-1kg', 6.00),
    ('feijao-preto-bernardo-1kg', 10.00),
    ('leite-integral-italac-1l', 9.00),
    ('inseticida-baygon-baratas-e-formigas-360ml', 11.99),
    ('inseticida-baygon-acao-total-360ml', 9.99),
    ('composto-lacteo-dobon-400g', 13.99),
    ('cereal-nestle-snow-flakes-caixa-230g', 13.00),
    ('agua-sanitaria-ype-1l', 5.00),
    ('limpador-perfumado-ype-cha-branco-500ml', 8.00),
    ('detergente-minuano-limao-500ml', 3.00),
    ('detergente-minuano-marine-500ml', 3.00),
    ('arroz-brilhante-branco-1kg', 6.00),
    ('sabao-em-barra-ara-assim-neutro-800g', 15.00),
    ('sabao-em-barra-alpes-glicerinado-super-150g', 3.50),
    ('sabao-em-barra-alpes-limao-150g', 3.50),
    ('desinfetante-ype-bak-500ml', 4.50),
    ('desinfetante-ype-pinho-tradicao-500ml', 7.00),
    ('veja-perfumes-frutas-tropicais-500ml', 8.00),
    ('desinfetante-pinho-bril-floral-500ml', 8.00),
    ('desinfetante-pinho-bril-flores-de-limao-500ml', 8.00),
    ('vanish-po-240g-oxi-action-crystal-white', 12.00),
    ('vanish-po-240g-oxi-action-pink', 12.00),
    ('sabao-liquido-uzzilim-cuidado-total-1l', 12.00),
    ('sabao-liquido-urca-verde-1l', 14.99),
    ('sabao-liquido-urca-lavanda-1l', 14.99),
    ('lava-roupas-liquido-omo-acao-cuidado-750ml', 20.00),
    ('mon-bijou-coco-500ml', 18.00),
    ('kelly-coca-cola-zero-2l', 12.00),
    ('refrigerante-coca-cola-2l', 12.00),
    ('biscoito-cream-cracker-sol-350g', 6.50),
    ('arroz-tio-alemao-parboilizado-1kg', 6.00),
    ('sabao-em-po-brisa-floral-bicarbonato-800g', 8.00),
    ('detergente-ype-neutro-500ml', 3.00),
    ('creme-dental-colgate-maxima-protecao-anticaries-120g', 4.75),
    ('papel-higienico-sublime-folha-simples-12-rolos-30m', 12.99),
    ('creme-dental-sorriso-tripla-limpeza-70g', 3.75),
    ('feijao-preto-kumbuca-1kg', 10.00),
    ('sabao-em-po-tixan-ype-primavera-800g', 13.99),
    ('sabao-em-barra-minuano-neutro-5x160g-800g', 15.00),
    ('bolacha-cream-cracker-marilan-premium-300g', 6.50),
    ('biscoito-marilan-rosquinha-coco-300g', 6.00),
    ('biscoito-marilan-rosquinha-chocolate-300g', 6.00),
    ('biscoito-doce-mabel-chocolate', 8.00),
    ('biscoito-maisena-mabel', 8.00),
    ('biscoito-maizena-tradicional-vitarella', 8.00),
    ('biscoito-doce-belma-coco-zero-lactose', 6.00),
    ('biscoito-doce-belma-leite-zero-lactose', 6.00),
    ('biscoito-doce-belma-maizena-zero-lactose', 6.00),
    ('agua-mineral-cristal-5l', 9.00),
    ('arroz-phd-polido-1kg', 5.50),
    ('biscoito-doce-laminado-vivale-leite-300g', 6.75),
    ('kit-pantene-shampoo-350ml-condicionador-175ml-liso-extremo', 38.00),
    ('bebida-lactea-morango-bob-esponja-200ml', 3.00),
    ('macarrao-instantaneo-sandella-galinha-85g', 2.00),
    ('sabonete-albany-leite-de-coco-85g', 2.50),
    ('creme-dental-colgate-tripla-acao-120g', 8.75),
    ('biscoito-wafer-minueto-brigadeiro-73g', 2.00),
    ('creme-dental-colgate-tripla-acao-180g', 10.00),
    ('pao-de-queijo-pao-e-arte-tradicional-1kg', 26.00),
    ('pao-de-queijo-norte-minas-1kg', 25.00),
    ('biscoito-wafer-minueto-pe-de-moleque-73g', 2.00),
    ('sabonete-albany-perfumes-da-natureza-frutas-vermelhas-85g', 2.50),
    ('sabao-em-po-omo-lavagem-perfeita-1-4kg', 25.00),
    ('batata-mccain-corte-fino-7mm-2-25kg', 54.00),
    ('limpador-perfumado-casa-flor-500ml', 5.50),
    ('detergente-zupp-acai-500ml', 3.00),
    ('detergente-zupp-ultra-500ml', 3.00),
    ('detergente-zupp-clear-500ml', 3.00),
    ('sabao-barra-brisa-glicerinado-neutro-800g', 13.00),
    ('amaciante-brisa-carinho-2l', 11.00),
    ('multi-inseticida-pro-inset-acao-total-350ml', 12.00),
    ('multi-inseticida-pro-inset-eucalipto-350ml', 12.00),
    ('multi-inseticida-pro-inset-mata-baratas-e-formigas-350ml', 12.00),
    ('amaciante-minuano-brisa-macia-2l', 13.00),
    ('amaciante-minuano-noite-de-lua-2l', 13.00),
    ('pao-de-queijo-pao-e-arte-tradicional-400g', 12.00),
    ('pao-de-queijo-coquetel-norte-minas-400g', 12.00),
    ('sabao-barra-brisa-lavanda-e-coco-lilas-800g', 13.00),
    ('sabao-barra-brisa-glicerinado-limao-800g', 13.00),
    ('desinfetante-ype-bak-floral-500ml', 4.50),
    ('limpador-perfumado-veja-lavanda-500ml', 8.00),
    ('vanish-oxi-action-pink-sache-sem-cloro-120g', 10.00),
    ('vanish-po-sem-cloro-white-120g', 10.00),
    ('tira-manchas-vanish-oxi-action-400g', 27.00),
    ('sabao-liquido-mon-bijou-neutro-300ml', 17.00),
    ('lava-roupas-liquido-omo-acao-total-750ml', 20.00),
    ('batata-palito-farm-frites-potato-2-5kg', 54.00),
    ('cerveja-corona-extra-6-garrafas-330ml', 51.00),
    ('creme-dental-colgate-carvao-natural-extracts-70g', 11.00),
    ('sabao-em-po-brisa-floral-bicarbonato-400g', 4.50),
    ('sabao-em-po-brisa-lavanda-e-coco-400g', 4.50),
    ('lava-roupas-em-po-zupp-800g', 11.00),
    ('sabao-em-po-brisa-lavanda-e-coco-800g', 8.00),
    ('detergente-ype-clear-care-500ml', 3.00),
    ('desodorante-nivea-original-protect-150ml', 17.00),
    ('desodorante-francis-aerossol-azul-men-active-sport-150ml', 17.00),
    ('desodorante-aero-francis-men-ultra-fresh', 17.00),
    ('desodorante-above-peaceful-farhion-150ml', 9.00),
    ('presunto-cozido-preco-por-kg', 29.99),
    ('cerveja-amstel-lata-269ml-cx-12', 40.00),
    ('creme-dental-sorriso-kolynos-90g', 4.50),
    ('detergente-zupp-limao-500ml', 3.00),
    ('caixa-cerveja-skol-pilsen-15x269ml', 52.00),
    ('batata-palito-star-frites-2kg', 38.00),
    ('desodorante-aero-above-sport-150ml', 9.00),
    ('desodorante-above-women-lady-150ml', 9.00),
    ('biscoito-marilan-pit-stop-original-137g', 5.75),
    ('biscoito-rosquinha-tradicional-marilan-sabor-coco-500g', 8.00),
    ('caixa-cerveja-antarctica-pilsen-15x269ml', 52.00),
    ('leite-de-coco-qualicoco-vd-500ml', 10.00),
    ('leite-de-coco-qualicoco-vd-200ml', 5.50),
    ('leite-de-coco-copra-vd-200ml', 6.00),
    ('caixa-cerveja-brahma-chopp-15x269ml', 50.00)
),
resolved as (
  select p.id as product_id, d.value, e.id as establishment_id
  from desired d
  join public.products p on p.slug = d.slug
  cross join lateral (
    select id from public.establishments where name = 'COMERCIAL VANDERLEY' limit 1
  ) e
),
latest as (
  select distinct on (pr.product_id) pr.id, pr.product_id
  from public.prices pr
  join resolved r on r.product_id = pr.product_id and r.establishment_id = pr.establishment_id
  order by pr.product_id, pr.captured_at desc, pr.id desc
),
updated as (
  update public.prices pr
  set previous_value = case when pr.value <> r.value then pr.value else pr.previous_value end,
      value = r.value,
      captured_at = now()
  from resolved r
  join latest l on l.product_id = r.product_id
  where pr.id = l.id
  returning pr.product_id
)
insert into public.prices (product_id, establishment_id, value, previous_value, captured_at)
select r.product_id, r.establishment_id, r.value, null, now()
from resolved r
where not exists (select 1 from latest l where l.product_id = r.product_id);
